[package]
name = "rsh"
version = "0.1.0"
edition = "2018"
authors = ["Alex Daultukaev, Oleg Icefield"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
sys-info = "*"

[build-dependencies]
cc = "1.0"
